services:
  # app:
  #   image: graceful_shutdown
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.13.0
    container_name: graceful-shotdown-jaeger
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
