services:
  # app:
  #   image: graceful_shutdown
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.13.0
    container_name: graceful-shotdown-jaeger
    ports:
      - "16686:16686" # Jaeger UI

  otel-collector:
    image: otel/opentelemetry-collector:0.142.0
    container_name: graceful-shutdown-collecctor
    ports:
      - "4317:4317" # OTLP gRPC
      - "8889:8889" # Prometheus scrape endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector/config.yaml
    command:
      - "--config=/etc/otel-collector/config.yaml"
    depends_on:
      - jaeger
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: graceful-shotdown-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - otel-collector

volumes:
  prometheus_data:
